//! Config-file resolution, deserialization, and validation.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

use serde::Deserialize;
use toml::Spanned;
use tracing::warn;

use crate::error::{AnalysisError, Result};

use super::{LayerRule, ModulePattern, RuleSet};

/// Preferred config file name (searched first).
const CONFIG_FILE: &str = "crawk.toml";
/// Hidden config file name, searched as a fallback.
const CONFIG_FILE_HIDDEN: &str = ".crawk.toml";

/// Serde shape of the whole config file: a single `[check]` table.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct RawConfig {
    check: RawCheck,
}

/// Serde shape of the `[check]` table.
#[derive(Debug, Default, Deserialize)]
#[serde(default, rename_all = "kebab-case", deny_unknown_fields)]
struct RawCheck {
    layers: Vec<RawLayer>,
    strict_layers: bool,
    deny_same_layer: bool,
}

/// Serde shape of one `[[check.layers]]` group.
///
/// `name` is [`Spanned`](Spanned) so a duplicate group name can be
/// reported with the source line it occurs on.
#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct RawLayer {
    name: Spanned<String>,
    order: Vec<String>,
}

/// Resolve which rule-config file to use.
///
/// With an explicit path, that file is used verbatim (error if missing). Without
/// one, the crate root is searched for `crawk.toml` then `.crawk.toml`; the plain
/// name wins when both exist (with a warning). Missing config is an operational
/// error so a typo'd filename fails CI rather than silently passing.
pub(crate) fn resolve_config_path(crate_root: &Path, explicit: Option<&Path>) -> Result<PathBuf> {
    if let Some(path) = explicit {
        if path.is_file() {
            return Ok(path.to_path_buf());
        }
        return Err(AnalysisError::RuleConfigError {
            path: path.to_path_buf(),
            reason: "config file does not exist".to_owned(),
        });
    }

    let plain = crate_root.join(CONFIG_FILE);
    let hidden = crate_root.join(CONFIG_FILE_HIDDEN);
    match (plain.is_file(), hidden.is_file()) {
        (true, true) => {
            warn!("both {CONFIG_FILE} and {CONFIG_FILE_HIDDEN} found, using {CONFIG_FILE}");
            Ok(plain)
        }
        (true, false) => Ok(plain),
        (false, true) => Ok(hidden),
        (false, false) => Err(AnalysisError::RuleConfigError {
            path: crate_root.to_path_buf(),
            reason: format!(
                "no {CONFIG_FILE} or {CONFIG_FILE_HIDDEN} found in {}; \
                 run `crawk check --init` to generate a starter config",
                crate_root.display()
            ),
        }),
    }
}

/// Render a starter `crawk.toml` body from the crate's modules.
///
/// Emits a single `[[check.layers]]` group named after the crate, listing its
/// top-level modules alphabetically, with a comment telling the user to order
/// them. crawk deliberately does not guess the hierarchy — layer ordering
/// encodes intent the source cannot reveal.
pub(crate) fn scaffold(crate_name: &str, modules: &BTreeSet<String>) -> String {
    // Collapse to top-level segments; the BTreeSet dedups and sorts them.
    let top: BTreeSet<&str> = modules
        .iter()
        .filter_map(|m| m.split("::").next())
        .collect();
    let order = top
        .iter()
        .map(|name| format!("\"{name}\""))
        .collect::<Vec<_>>()
        .join(", ");
    format!(
        "# Generated by `crawk check --init`. Reorder `order` so the highest\n\
         # layer comes first: a lower layer must not depend on a higher one.\n\
         # Split into multiple groups as needed; a module may appear in several,\n\
         # each checked independently. See `crawk check\n\
         # --help` for the full `layers` semantics.\n\
         \n\
         [[check.layers]]\n\
         name = \"{crate_name}\"\n\
         order = [{order}]\n"
    )
}

/// Write a starter rule config, returning its path.
///
/// With an explicit path (`--config`/`-c`), writes there. Otherwise, writes
/// `crawk.toml` in `crate_root`. Either way it refuses (operational error) when
/// the target — or, for the default case, any discovered `crawk.toml` /
/// `.crawk.toml` — already exists, so `--init` never clobbers a real config.
///
/// # Errors
///
/// [`AnalysisError::RuleConfigError`] when a config already exists or the file
/// cannot be written.
pub(crate) fn scaffold_config(
    crate_root: &Path,
    explicit: Option<&Path>,
    crate_name: &str,
    modules: &BTreeSet<String>,
) -> Result<PathBuf> {
    let path = if let Some(target) = explicit {
        if target.exists() {
            return Err(AnalysisError::RuleConfigError {
                path: target.to_path_buf(),
                reason: "config already exists; edit it directly or remove it first".to_owned(),
            });
        }
        target.to_path_buf()
    } else {
        if let Ok(existing) = resolve_config_path(crate_root, None) {
            return Err(AnalysisError::RuleConfigError {
                path: existing,
                reason: "config already exists; edit it directly or remove it first".to_owned(),
            });
        }
        crate_root.join(CONFIG_FILE)
    };
    std::fs::write(&path, scaffold(crate_name, modules)).map_err(|e| {
        AnalysisError::RuleConfigError {
            path: path.clone(),
            reason: e.to_string(),
        }
    })?;
    Ok(path)
}

/// 1-based line number of byte `offset` within `text`.
fn line_of(text: &str, offset: usize) -> usize {
    let end = offset.min(text.len());
    text[..end].bytes().filter(|&b| b == b'\n').count() + 1
}

/// Reject duplicate `[[check.layers]]` group names, pinning the duplicate to its
/// source line via the [`Spanned`](Spanned) name.
fn check_unique_names(path: &Path, text: &str, layers: &[RawLayer]) -> Result<()> {
    let mut seen = BTreeSet::new();
    for layer in layers {
        if !seen.insert(layer.name.get_ref().as_str()) {
            let line = line_of(text, layer.name.span().start);
            return Err(AnalysisError::RuleConfigError {
                path: path.to_path_buf(),
                reason: format!(
                    "duplicate layer group name '{}' (line {line})",
                    layer.name.get_ref()
                ),
            });
        }
    }
    Ok(())
}

impl RuleSet {
    /// Read, parse, and validate a rule-config file against the crate's modules.
    ///
    /// # Errors
    ///
    /// - [`AnalysisError::RuleConfigError`] — file unreadable, malformed TOML,
    ///   overlapping layer groups, or (under `strict-layers`) an uncovered module.
    /// - [`AnalysisError::UnknownRuleModule`] — a rule names a module that does
    ///   not exist in the crate.
    pub(crate) fn load(path: &Path, modules: &BTreeSet<String>) -> Result<Self> {
        let text = std::fs::read_to_string(path).map_err(|e| AnalysisError::RuleConfigError {
            path: path.to_path_buf(),
            reason: e.to_string(),
        })?;
        let raw: RawConfig = toml::from_str(&text).map_err(|e| AnalysisError::RuleConfigError {
            path: path.to_path_buf(),
            reason: e.to_string(),
        })?;
        // Group names must be unique (violations are reported per group and name
        // it). Checked here, where the spans into `text` are still available, so
        // the duplicate can be pinned to its source line.
        check_unique_names(path, &text, &raw.check.layers)?;
        let rules = Self::from_raw(raw.check);
        rules.validate(path, modules)?;
        Ok(rules)
    }

    /// Convert the deserialized shape into the validated in-memory form.
    fn from_raw(raw: RawCheck) -> Self {
        let layers = raw
            .layers
            .into_iter()
            .map(|raw_layer| LayerRule {
                name: raw_layer.name.into_inner(),
                order: raw_layer
                    .order
                    .iter()
                    .map(|entry| ModulePattern::parse_subtree(entry))
                    .collect(),
            })
            .collect();
        Self {
            layers,
            strict_layers: raw.strict_layers,
            deny_same_layer: raw.deny_same_layer,
        }
    }

    /// Validate rules against the crate's known modules.
    fn validate(&self, path: &Path, modules: &BTreeSet<String>) -> Result<()> {
        // 1. Every layer pattern must reference a real module (catch typos).
        for layer in &self.layers {
            for pattern in &layer.order {
                if !pattern.references_known(modules) {
                    return Err(AnalysisError::UnknownRuleModule {
                        module: pattern.display(),
                        rule: format!("layers '{}'", layer.name),
                    });
                }
            }
        }
        // 2. Under strict mode, every module must be covered by some group.
        //    Groups may overlap, so coverage just means at least one membership.
        if self.strict_layers {
            for module in modules {
                if self.memberships(module).is_empty() {
                    return Err(AnalysisError::RuleConfigError {
                        path: path.to_path_buf(),
                        reason: format!(
                            "strict-layers: module '{module}' is not assigned to any layer"
                        ),
                    });
                }
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    fn write_config(dir: &Path, name: &str, body: &str) -> PathBuf {
        let path = dir.join(name);
        let mut file = std::fs::File::create(&path).expect("create config");
        file.write_all(body.as_bytes()).expect("write config");
        path
    }

    fn module_set(names: &[&str]) -> BTreeSet<String> {
        names.iter().map(ToString::to_string).collect()
    }

    #[test]
    fn explicit_path_used_verbatim() {
        let dir = tempfile::tempdir().expect("tempdir");
        let cfg = write_config(dir.path(), "custom.toml", "[check]\n");
        let resolved = resolve_config_path(dir.path(), Some(&cfg)).expect("resolve");
        assert_eq!(resolved, cfg);
    }

    #[test]
    fn explicit_missing_path_errors() {
        let dir = tempfile::tempdir().expect("tempdir");
        let missing = dir.path().join("nope.toml");
        assert!(resolve_config_path(dir.path(), Some(&missing)).is_err());
    }

    #[test]
    fn plain_name_wins_over_hidden() {
        let dir = tempfile::tempdir().expect("tempdir");
        write_config(dir.path(), "crawk.toml", "[check]\n");
        write_config(dir.path(), ".crawk.toml", "[check]\n");
        let resolved = resolve_config_path(dir.path(), None).expect("resolve");
        assert_eq!(resolved, dir.path().join("crawk.toml"));
    }

    #[test]
    fn hidden_name_used_when_alone() {
        let dir = tempfile::tempdir().expect("tempdir");
        write_config(dir.path(), ".crawk.toml", "[check]\n");
        let resolved = resolve_config_path(dir.path(), None).expect("resolve");
        assert_eq!(resolved, dir.path().join(".crawk.toml"));
    }

    #[test]
    fn no_config_errors() {
        let dir = tempfile::tempdir().expect("tempdir");
        assert!(resolve_config_path(dir.path(), None).is_err());
    }

    #[test]
    fn unknown_module_in_layer_is_error() {
        let dir = tempfile::tempdir().expect("tempdir");
        let cfg = write_config(
            dir.path(),
            "crawk.toml",
            "[[check.layers]]\nname = \"app\"\norder = [\"cli\", \"typo_mod\"]\n",
        );
        let modules = module_set(&["cli", "analyzer"]);
        let err = RuleSet::load(&cfg, &modules).expect_err("should reject unknown module");
        assert!(matches!(err, AnalysisError::UnknownRuleModule { .. }));
    }

    #[test]
    fn overlapping_groups_are_allowed() {
        let dir = tempfile::tempdir().expect("tempdir");
        // `parser` belongs to both groups; overlap is no longer a config error.
        let cfg = write_config(
            dir.path(),
            "crawk.toml",
            "[[check.layers]]\nname = \"a\"\norder = [\"cli\", \"parser\"]\n\
             [[check.layers]]\nname = \"b\"\norder = [\"parser\", \"discover\"]\n",
        );
        let modules = module_set(&["cli", "parser", "discover"]);
        assert!(RuleSet::load(&cfg, &modules).is_ok());
    }

    #[test]
    fn duplicate_group_names_are_error() {
        let dir = tempfile::tempdir().expect("tempdir");
        let cfg = write_config(
            dir.path(),
            "crawk.toml",
            "[[check.layers]]\nname = \"app\"\norder = [\"cli\"]\n\
             [[check.layers]]\nname = \"app\"\norder = [\"analyzer\"]\n",
        );
        let modules = module_set(&["cli", "analyzer"]);
        let err = RuleSet::load(&cfg, &modules).expect_err("should reject duplicate names");
        assert!(matches!(&err, AnalysisError::RuleConfigError { .. }));
        if let AnalysisError::RuleConfigError { reason, .. } = err {
            // The duplicate "app" sits on line 5 of the config; the message pins it.
            assert!(
                reason.contains("duplicate layer group name 'app'"),
                "{reason}"
            );
            assert!(reason.contains("line 5"), "{reason}");
        }
    }

    #[test]
    fn strict_layers_requires_full_coverage() {
        let dir = tempfile::tempdir().expect("tempdir");
        let cfg = write_config(
            dir.path(),
            "crawk.toml",
            "[check]\nstrict-layers = true\n\
             [[check.layers]]\nname = \"app\"\norder = [\"cli\"]\n",
        );
        let modules = module_set(&["cli", "uncovered"]);
        let err = RuleSet::load(&cfg, &modules).expect_err("should require coverage");
        assert!(matches!(err, AnalysisError::RuleConfigError { .. }));
    }

    #[test]
    fn unknown_top_level_key_is_rejected() {
        let dir = tempfile::tempdir().expect("tempdir");
        let cfg = write_config(dir.path(), "crawk.toml", "[check]\nlayerz = []\n");
        let modules = module_set(&["cli"]);
        assert!(RuleSet::load(&cfg, &modules).is_err());
    }

    #[test]
    fn scaffold_lists_top_level_modules() {
        let modules = module_set(&["cli", "analyzer", "web", "web::api", "web::repo"]);
        let body = scaffold("my_crate", &modules);
        assert!(body.contains("[[check.layers]]"));
        // Group is named after the crate.
        assert!(body.contains("name = \"my_crate\""));
        // Top-level segments only, deduplicated and alphabetical.
        assert!(body.contains(r#"order = ["analyzer", "cli", "web"]"#));
        assert!(!body.contains("web::api"));
    }

    #[test]
    fn scaffold_config_writes_when_absent() {
        let dir = tempfile::tempdir().expect("tempdir");
        let modules = module_set(&["cli", "analyzer"]);
        let path = scaffold_config(dir.path(), None, "my_crate", &modules).expect("scaffold");
        assert_eq!(path, dir.path().join("crawk.toml"));
        let body = std::fs::read_to_string(&path).expect("read back");
        assert!(body.contains("[[check.layers]]"));
    }

    #[test]
    fn scaffold_config_honours_explicit_path() {
        let dir = tempfile::tempdir().expect("tempdir");
        let target = dir.path().join("custom.toml");
        let modules = module_set(&["cli"]);
        let path = scaffold_config(dir.path(), Some(&target), "my_crate", &modules)
            .expect("scaffold to explicit path");
        assert_eq!(path, target);
        assert!(target.is_file());
    }

    #[test]
    fn scaffold_config_refuses_existing_explicit_path() {
        let dir = tempfile::tempdir().expect("tempdir");
        let target = write_config(dir.path(), "custom.toml", "[check]\n");
        let modules = module_set(&["cli"]);
        // Explicit target that exists is refused even though discovery finds nothing.
        assert!(scaffold_config(dir.path(), Some(&target), "my_crate", &modules).is_err());
    }

    #[test]
    fn scaffold_config_refuses_when_config_exists() {
        let dir = tempfile::tempdir().expect("tempdir");
        write_config(dir.path(), "crawk.toml", "[check]\n");
        let modules = module_set(&["cli"]);
        assert!(scaffold_config(dir.path(), None, "my_crate", &modules).is_err());
    }

    #[test]
    fn scaffold_config_refuses_when_hidden_config_exists() {
        let dir = tempfile::tempdir().expect("tempdir");
        write_config(dir.path(), ".crawk.toml", "[check]\n");
        let modules = module_set(&["cli"]);
        // Reuses discovery, so the hidden name blocks scaffolding too.
        assert!(scaffold_config(dir.path(), None, "my_crate", &modules).is_err());
    }

    #[test]
    fn valid_config_loads() {
        let dir = tempfile::tempdir().expect("tempdir");
        let cfg = write_config(
            dir.path(),
            "crawk.toml",
            "[[check.layers]]\nname = \"app\"\norder = [\"cli\", \"analyzer\"]\n",
        );
        let modules = module_set(&["cli", "analyzer"]);
        assert!(RuleSet::load(&cfg, &modules).is_ok());
    }
}
